package main

import (
	"math/rand"
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

// generate random data for bar chart
func generateBarItems() []opts.BarData {
	items := make([]opts.BarData, 0)
	for i := 0; i < 7; i++ {
		items = append(items, opts.BarData{Value: rand.Intn(300)})
	}
	return items
}

func main() {
	// create a new bar instance
	bar := charts.NewLine()
	// set some global options like Title/Legend/ToolTip or anything else
	bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "My first bar chart generated by go-echarts",
		Subtitle: "It's extremely easy to use, right?",
	}))

	// Put data into instance
	bar.SetXAxis([]string{"A", "B", "C", "D", "E", "F", "G"}).
		AddSeries("Category A", []opts.LineData{{Value: 120}, {Value: 200}, {Value: 150}, {Value: 80}, {Value: 70}, {Value: 110}, {Value: 130}}).
		AddSeries("Category B", []opts.LineData{{Value: 220}, {Value: 180}, {Value: 250}, {Value: 280}, {Value: 270}, {Value: 210}, {Value: 230}})
	// Where the magic happens
	f, _ := os.Create("bar.html")
	bar.Render(f)
}
